services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    env_file:
      - .env
  db:
    image: postgres
    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin123
#      POSTGRES_DB: modulite
      POSTGRES_HOST: dpg-cr3ltpt6l47c73a7m3ag-a
      POSTGRES_USER: modulite_db_user
      POSTGRES_PASSWORD: vNfd7OfxHBdV77fM9yRdp8XkXrdtXDlU
      POSTGRES_DB: modulite_db
    ports:
      - "5432:5432"

