name: Rust Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_check:
    name: Check Rust project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy # Optional, if you want to run clippy

      - name: Check with cargo
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features -- -D warnings
        # The `-D warnings` argument configures the compiler to treat all warnings as errors

      - name: Clippy
        if: success() # Runs Clippy if the check step was successful
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings
        # This also treats any Clippy warning as an error
